// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5PDZwv_JWutNXfYF1GDyAreQKTlVBWak',
    appId: '1:303335084020:android:5f0291524b6446509733a1',
    messagingSenderId: '303335084020',
    projectId: 'cuidarpet-49d6b',
    storageBucket: 'cuidarpet-49d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7A2h0RH2EfzKtWS816PPYiqxZqVaRTZI',
    appId: '1:303335084020:ios:bbc01f4c00f69c2a9733a1',
    messagingSenderId: '303335084020',
    projectId: 'cuidarpet-49d6b',
    storageBucket: 'cuidarpet-49d6b.firebasestorage.app',
    iosBundleId: 'com.example.cuidarPetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAaZ6STX6piR_Vii3rwTH8ONSiHaUDqhU',
    appId: '1:303335084020:web:5f6215fb7c164c099733a1',
    messagingSenderId: '303335084020',
    projectId: 'cuidarpet-49d6b',
    authDomain: 'cuidarpet-49d6b.firebaseapp.com',
    storageBucket: 'cuidarpet-49d6b.firebasestorage.app',
    measurementId: 'G-B7BJ6PFPY2',
  );
}
